name: Upstream Sync

on:
  schedule:
    - cron: "0 */12 * * *"  # 每 6 小时运行一次
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest

    steps:
      - name: Checkout target repo
        uses: actions/checkout@v4

      - name: Sync upstream changes
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.5
        with:
          upstream_sync_repo: senshinya/MoonTV
          upstream_sync_branch: main   #  注意确认上游默认分支是否为 main
          target_sync_branch: main     #  注意确认你自己的默认分支是否为 main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Notify if sync failed
        if: failure()
        run: |
          echo "[Error] Upstream sync failed. 请检查 upstream 仓库是否修改了 workflow 文件，或手动同步。"
          exit 1

      - name: Clean up old workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
